version: '3.7'
services:
  dog-frontend:
    build:
      context: ./react-query-test
      args:
        - NEXT_PUBLIC_BACKEND_HOST=http://localhost:3000
    image: dog-frontend-prod
    working_dir: /app
    restart: on-failure
    environment:
      - NEXT_PUBLIC_BACKEND_HOST=http://localhost:3000
    ports:
      - '8080:8080'
    depends_on:
      - dog-api

  dog-api:
    build:
      context: ./dog-api
    image: dog-api-prod
    working_dir: /app
    restart: on-failure
    environment:
      - TYPEORM_HOST=dog-db
      - TYPEORM_PORT=5432
      - TYPEORM_USERNAME=dog
      - TYPEORM_PASSWORD=password
      - TYPEORM_DATABASE=dog
      - TYPEORM_MIGRATIONS_TABLE_NAME=migrations
      - TYPEORM_MIGRATIONS_DIR=src/migrations
    ports:
      - '3000:3000'
    depends_on:
      - dog-db

  dog-db:
    image: postgres
    environment:
      - POSTGRES_USER=dog
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=dog
    ports:
      - '5432:5432'